# Generated by Django 5.1.2 on 2024-11-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_staffprofile_assigned_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="assigned_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.subject",
            ),
        ),
    ]
