# Generated by Django 5.1.2 on 2024-11-07 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_question_assigned_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="course",
        ),
    ]
