# Generated by Django 5.1.2 on 2024-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_exam_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="courses",
            field=models.ManyToManyField(
                related_name="student_courses", to="home.course"
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
