# Generated by Django 5.1.2 on 2024-11-08 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="assigned_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.course",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="staff",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.staff"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("student", "question")},
        ),
    ]
